Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.box = "uros333/freeBSD12withGo"
  config.vm.box_version = "0.0.1"
  #config.vm.box = "freebsd/FreeBSD-12.0-CURRENT"
  #config.vm.box_version = "2018.08.03"
  config.vm.base_mac = "00deadbeef00"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.shell = "sh"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", path: "runtests.sh"
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end
end
