Vagrant.configure("2") do |config|
  config.vm.box = "kja/netbsd-7-amd64"
  config.vm.box_version = "2015.11.10.01"
  config.vm.base_mac = "00deadbeef00"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.shell = "sh"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", path: "runtests.sh"

  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end
end
